### PR TITLE
Colorified the output (Hardcorded color for now) ✨

### PR DESCRIPTION
**Pull request by FahadLive**
Pull request to implement #2 🎉

**New crate**
- [colored](https://crates.io/crates/colored) 🌈

Currently, the output gives a bright green (bold green). If this PR gets merged, I will try and add customization options. ⚙

### CODE REVIEW

**Comment by rabbit-time** [comment]
I'll test it once I have the time and merge when ready, thanks for the PR!

**Review by rabbit-time — CHANGES_REQUESTED** [review]
Alright! I've finally reviewed this and so far I've noticed one problem. When I tested locally, this PR broke the "Quote x of y" line, so only the quote line is shown.

**Comment by FahadLive** [comment]
Oh, good catch. I will look into fixing it

**Comment by FahadLive** [comment]
I have fixed the issue. And I have synced the latest changes from this repo.

**Pull request merged**
